spring:
  profiles:
    active: dev
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    com.lfeher.gateway: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    name: "Gateway server"
